### ISSUE TITLE
你可以尝试添加一个新的API，例如ProxiedPlayer的一个setTabHeader

### ISSUE THREAD

**Issue by tianxiu2b2t** [mouse0w0/BungeeCord-CN-Translation#3]
就是通过Bungeecord的发包来设置每个服务器玩家的tab栏

**Comment by mouse0w0** [comment]
本教程目前就仅是[《BungeeCord插件开发》](https://www.spigotmc.org/wiki/bungeecord-plugin-development/)的中文翻译，至于API中提供的其它功能，请自行学习使用。
